version: '2'
services:
  app:
    image: miguelpeixe/date-service:latest
    # Comment-out below to pull image from docker hub
    build: .
    # Comment-out below for production
    command: nodemon index.js
    ports:
    - 3000:3000
    volumes:
    # Development volumes. Comment-out for production
    - /src/node_modules
    - .:/src
    environment:
      NODE_ENV: development
      WHITELIST_DOMAINS: https://form.example.com, https://www.example.com
